from __future__ import annotations

import os
from pathlib import Path

SERVER_NAME = "reversing-mcp"
SERVER_VERSION = "0.1.0"
STATE_DIRNAME = ".reversing-mcp"
SESSION_SCHEMA_VERSION = 1
DEFAULT_PAGE_LIMIT = 50
MAX_PAGE_LIMIT = 200
DEFAULT_WORKSPACE_ROOT = "/workspace"
DEFAULT_MAX_INPUT_SIZE_BYTES = 250 * 1024 * 1024
DEFAULT_MAX_ARTIFACTS_PER_SESSION = 128
DEFAULT_PARSER_TIMEOUT_SECONDS = 30
DEFAULT_PARSER_MEMORY_MB = 1024
DEFAULT_PARSER_CPU_SECONDS = 15
DEFAULT_RECURSION_DEPTH_LIMIT = 4
DEFAULT_DECOMPILATION_CHAR_LIMIT = 100_000
DEFAULT_STRING_COUNT_LIMIT = 50_000
DEFAULT_CARVED_BYTE_BUDGET = 100 * 1024 * 1024


def get_workspace_root() -> Path:
    return Path(os.environ.get("REVERSING_MCP_WORKSPACE_ROOT", DEFAULT_WORKSPACE_ROOT)).resolve()


def get_state_root() -> Path:
    return get_workspace_root() / STATE_DIRNAME
