from __future__ import annotations

from worksheet_generator.reward_content_generation import GeminiRewardContentGenerator
from worksheet_generator.models import ApprovalState, LearnerBand, RewardContentCandidate
from worksheet_generator.reward_content_generation import RewardContentGenerationRequest
from worksheet_generator.reward_content_review import RewardContentStateError
from worksheet_generator.reward_content_service import RewardContentService


class FakeGenerator:
    def __init__(self) -> None:
        self.calls: list[RewardContentGenerationRequest] = []
        self.solution_calls: list[tuple[RewardContentGenerationRequest, str]] = []

    def generate(self, request: RewardContentGenerationRequest) -> RewardContentCandidate:
        self.calls.append(request)
        return RewardContentCandidate(
            prompt_text="What clue matches the theme fractions?",
            solution_phrase="Fractions",
            theme=request.theme,
            source="fake_generator",
            approval_state=ApprovalState.PENDING,
            style=request.preferred_style,
            language=request.language,
            review_notes=["Generated by fake generator."],
        )

    def generate_for_solution(self, request: RewardContentGenerationRequest, solution_phrase: str) -> RewardContentCandidate:
        self.solution_calls.append((request, solution_phrase))
        return RewardContentCandidate(
            prompt_text="What classroom clue fits this idea without naming it?",
            solution_phrase=solution_phrase,
            theme=request.theme,
            source="fake_generator",
            approval_state=ApprovalState.PENDING,
            style=request.preferred_style,
            language=request.language,
            review_notes=["Generated from fixed solution by fake generator."],
        )


def test_direct_candidate_starts_pending_and_is_assessed() -> None:
    service = RewardContentService(generator=FakeGenerator())

    candidate = service.create_direct_candidate(
        LearnerBand.UPPER_ELEMENTARY,
        "What classroom idea helps you solve with confidence?",
        "Practice",
        theme="classroom",
        style="question",
    )

    assert candidate.approval_state == ApprovalState.PENDING
    assert candidate.reading_level_assessment is not None
    assert candidate.reading_level_assessment.passed is True
    assert any("Direct-input" in note for note in candidate.review_notes)


def test_generate_candidate_uses_injected_generator() -> None:
    generator = FakeGenerator()
    service = RewardContentService(generator=generator)
    request = RewardContentGenerationRequest(
        theme="fractions",
        learner_band=LearnerBand.UPPER_ELEMENTARY,
        preferred_style="question",
    )

    candidate = service.generate_candidate(request)

    assert len(generator.calls) == 1
    assert candidate.source == "fake_generator"
    assert candidate.reading_level_assessment is not None


def test_rejected_candidate_cannot_be_approved() -> None:
    service = RewardContentService(generator=FakeGenerator())
    candidate = service.create_direct_candidate(
        LearnerBand.UPPER_ELEMENTARY,
        "What classroom clue helps you keep trying?",
        "Effort",
    )
    rejected = service.reject_candidate(candidate, "Not aligned with lesson theme.")

    try:
        service.approve_candidate(rejected, LearnerBand.UPPER_ELEMENTARY)
    except RewardContentStateError:
        pass
    else:
        raise AssertionError("expected rejected candidate approval to fail")


def test_generate_candidate_for_solution_uses_injected_generator() -> None:
    generator = FakeGenerator()
    service = RewardContentService(generator=generator)
    request = RewardContentGenerationRequest(
        theme="fractions",
        learner_band=LearnerBand.UPPER_ELEMENTARY,
        preferred_style="question",
    )

    candidate = service.generate_candidate_for_solution(request, "Equal Parts")

    assert len(generator.solution_calls) == 1
    assert generator.solution_calls[0][1] == "Equal Parts"
    assert candidate.solution_phrase == "Equal Parts"
    assert candidate.source == "fake_generator"
    assert candidate.reading_level_assessment is not None


def test_long_or_flagged_content_is_still_approvable_with_warning_note() -> None:
    service = RewardContentService(generator=FakeGenerator())
    candidate = service.create_direct_candidate(
        LearnerBand.EARLY_ARITHMETIC,
        "This prompt includes violence and far too many advanced classroom explanation words for the target band.",
        "Problem Solving",
    )

    assert candidate.reading_level_assessment is not None
    assert candidate.reading_level_assessment.passed is False
    approved = service.approve_candidate(candidate, LearnerBand.EARLY_ARITHMETIC)
    assert approved.approval_state == ApprovalState.APPROVED
    assert any("despite heuristic reading-level warnings" in note for note in approved.review_notes)


def test_gemini_prompt_requires_letters_and_spaces_only_solution_phrase() -> None:
    generator = GeminiRewardContentGenerator(api_key="test-key")
    prompt = generator._build_prompt(  # noqa: SLF001
        RewardContentGenerationRequest(
            theme="space",
            learner_band=LearnerBand.UPPER_ELEMENTARY,
            preferred_style="riddle",
            language="en",
            solution_length_guidance="Prefer a short phrase.",
        )
    )

    assert "letters and spaces only" in prompt
    assert "Do not use digits, punctuation" in prompt
    assert "Invalid examples: MATH!, 3D SHAPES, X-O FACTOR, PI DAY 2026." in prompt
    assert "Do not include the exact solution_phrase inside prompt_text." in prompt
    assert "Avoid using the exact theme word inside prompt_text" in prompt
    assert "Before writing prompt_text, think about characters, objects, places, actions, or topics closely related to the chosen answer." in prompt


def test_gemini_prompt_for_color_picture_requests_drawable_subject() -> None:
    generator = GeminiRewardContentGenerator(api_key="test-key")
    prompt = generator._build_prompt(  # noqa: SLF001
        RewardContentGenerationRequest(
            theme="space",
            learner_band=LearnerBand.EARLY_ARITHMETIC,
            preferred_style="riddle",
            language="en",
            reveal_mode="color_by_number",
            color_picture_source="gemini",
        )
    )

    assert "simple concrete picture subject" in prompt
    assert "The solution_phrase must be that same simple drawable subject" in prompt
    assert "Choose the solution_phrase from this supported drawable subject list only" in prompt
    assert "SMILE, HEART, STAR, MOON, SUN, FLOWER, APPLE, TREE, EVERGREEN, CAT, CLOWN FISH, BLUE TANG, BUTTERFLY, ROCKET." in prompt
    assert "Then think about characters, objects, places, actions, or situations closely related to that subject." in prompt
    assert "Do not say the subject word itself inside prompt_text." in prompt


def test_gemini_prompt_for_preset_color_picture_requires_preset_subject() -> None:
    generator = GeminiRewardContentGenerator(api_key="test-key")
    prompt = generator._build_prompt(  # noqa: SLF001
        RewardContentGenerationRequest(
            theme="space",
            learner_band=LearnerBand.EARLY_ARITHMETIC,
            preferred_style="question",
            language="en",
            reveal_mode="color_by_number",
            color_picture_source="preset",
            color_picture_preset="moon",
        )
    )

    assert "The preset picture subject is MOON." in prompt
    assert "The solution_phrase must be exactly MOON." in prompt
    assert "Think about characters, objects, places, actions, or situations closely related to that subject." in prompt
    assert "Do not say the preset subject word itself inside prompt_text." in prompt


def test_gemini_prompt_for_fixed_solution_avoids_direct_answer_words() -> None:
    generator = GeminiRewardContentGenerator(api_key="test-key")
    prompt = generator._build_prompt_for_solution(  # noqa: SLF001
        RewardContentGenerationRequest(
            theme="space",
            learner_band=LearnerBand.UPPER_ELEMENTARY,
            preferred_style="riddle",
            language="en",
        ),
        "Blue Tang",
    )

    assert "Fixed solution_phrase: Blue Tang" in prompt
    assert "The solution_phrase is already chosen and must remain exactly the fixed solution_phrase." in prompt
    assert "Do not include the exact solution_phrase inside prompt_text." in prompt
    assert "Do not include any individual word from the solution_phrase inside prompt_text." in prompt
    assert "Do not use a near-synonym, direct category label, obvious compound extension, or a signature part, tool, place, or accessory" in prompt
    assert "Prefer a broader situational clue, behavior, role, or scene that requires one extra step of inference." in prompt
    assert "Keep the clue varied and specific rather than repeating generic classroom wording." in prompt


def test_gemini_prompt_for_pun_requires_actual_pun_style() -> None:
    generator = GeminiRewardContentGenerator(api_key="test-key")
    prompt = generator._build_prompt(  # noqa: SLF001
        RewardContentGenerationRequest(
            theme="school fun",
            learner_band=LearnerBand.UPPER_ELEMENTARY,
            preferred_style="pun",
            language="en",
        )
    )

    assert "STYLE REQUIREMENT: The prompt_text must be a pun or joke setup, not a plain descriptive riddle." in prompt
    assert "Use playful wordplay, a joke-question format, or a light humorous twist connected to the related ideas." in prompt
    assert "Do not fall back to a generic riddle, definition clue, or straightforward thematic question." in prompt
